apiVersion: v1
kind: PersistentVolume
metadata:
  name: workout-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/bad/k8s/workout-tracker-app
    type: DirectoryOrCreate
  claimRef:
    namespace: default
    name: workout-db-pvc
